const General = {
    HOME:"Home",
    ABOUT:"About",
    LOGOUT:"Log Out",
    USERNAME:"Username",
    PASSWORD:"Password",
    EMAIL:"Email",
    LOGIN:"Log In",
    SIGNUP:"Sign Up",
    SUBMIT:"Submit",
    DASHBOARD:"Dashboard",
    SETTINGS:"Settings",
    PROFILE:"Profile",
    INPUT_CITY_TITLE:"City",
    INPUT_TEMPERATURE_TITLE:"Available Unit (Celcius is default)",
    INPUT_DARK_MODE_TITLE:"Use Dark Mode",
    INPUT_SAVE:"Save",
    LOGIN_TITLE:"Check Weather",
    SIGN_UP_TITLE:"Sign Up To Weather",
    BACK_TO_LOGIN:"Back To Log In",
    WRONG_INPUT_LOGIN:"Wrong username or password!",
    TODAY_FORECAST:"Today Forecast",
    AIR_CONDITIONS:"Air Conditions",
    NEXT_7_DAY_FORECAST:"Next 7 Day Forecast",
    UNIT_CELCIUS:"CELCIUS",
    UNIT_FAHRENHEIT:"FAHRENHEIT",
    WRONG_INPUT_PROFILE:"Wrong format username or email!",
    BTN_UPDATE:"Update",
    LOGIN_AS_GUEST:"Log In As Guest (demo)",
    LOGIN_WAIT_MESSAGE: "Please wait while we are logging you in",
    DASHBOARD_WAIT_MESSAGE: "Please wait while we are sending you the data",
  };
  
  export default General